dataset: "VCTK"

path:
  wav_path: "{PATH}/VCTK-Corpus-0.92/wav48_silence_trimmed"
  corpus_path: "{PATH}/VCTK-Corpus-0.92"
  lexicon_path: "lexicon/new_librispeech-lexicon.txt"
  raw_path: "{PATH}/VCTK-Corpus-0.92/raw_data"
  preprocessed_path: "{PATH}/VCTK-Corpus-0.92/preprocessed_data"

preprocessing:
  text:
    text_cleaners: ["english_cleaners2"]
    language: "en"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000